version: "3.7"

services:
    # Reverse proxy using Caddy to route traffic to containers.
    # See Caddyfile to configure subdomains to each container.       
  caddy:
      image: docker.io/library/caddy:2-alpine
      container_name: caddy
      restart: unless-stopped
      networks:
      - searxng      
      ports:
          - "80:80"
          - "443:443"
      volumes:
      - caddy-data:/data
      - caddy-config:/config
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:rw
      - $PWD/certs:/data/certs
      cap_drop:
        - ALL
      cap_add:
        - NET_BIND_SERVICE
      logging:
        driver: "json-file"
        options:
          max-size: "1m"
          max-file: "1"

  redis:
    container_name: redis
    image: cgr.dev/chainguard/valkey:latest
    command: --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  caddy-data:
  caddy-config:
  valkey-data:
